### ISSUE TITLE
more redundant variables

### ISSUE THREAD

**Issue by sen1** [skk1998/FireBird#3]
You have:
```
def read_book(self, recent_book, rating=None):
        self.rb_recently_read_book = recent_book
        self.rb_rating = rating
        if self.rb_rating is None:
            self.book[self.rb_recently_read_book] = 0
        else:
            self.book[self.rb_recently_read_book] = self.rb_rating
```
Dont just add user variables `rb_recently_read_book` or `rb_rating` without understanging the requirement if that is necessary. If you have millions of users, these extra variables will be huge increase of objects. The task simple, just add a book with a rating. I would do:
```
def read_book(self, book, rating=None):
        self.books[book] = rating
```

**Comment by skk1998** [comment]
Per specifications Rating value was expected between 0 and 4. Passing None doesn't convert it to 0.
