### ISSUE TITLE
Reduce redundancy

### ISSUE THREAD

**Issue by sen1** [skk1998/FireBird#4]
You have:
```
def get_average_rating(self):
        garb_total_ratings = 0
        garb_average_rating = 0
        for i in range(0, len(self.ratings)):
            garb_total_ratings += self.ratings[i]
        garb_average_rating = garb_total_ratings / len(self.ratings)
        return garb_average_rating
```
Why the line `garb_average_rating = 0` was necessary? its not. It does not need an intialization. I see this across your project. You have a lot of redundant variables which are not necessary.

**Comment by skk1998** [comment]
It's the coding practice I have been following for many years to keep simple and manageable code. This helps if someone else takes over the maintenance.
