### ISSUE TITLE
add_user method

### ISSUE THREAD

**Issue by sen1** [skk1998/FireBird#6]
You have:
```
def add_user(self, name, email, user_books=None):
        self.au_name = name
        self.au_email = email
        self.au_user_books = user_books

        if self.validate_email_format(self.au_email) is False:
            return print("User: {usr} not added. Email id: {eml} has invalid format".format(eml=self.au_email, usr=self.au_name))

        if self.check_email_used(self.au_email) is True:
            return print("User: {usr} not added. Email id: {eml} already used by another user.".format(eml=self.au_email, usr=self.au_name))

        new_user = User(self.au_name, self.au_email)
        self.users[self.au_email] = new_user

        if self.au_user_books is not None:
            for i in range(0, len(self.au_user_books)):
                self.add_book_to_user(self.au_user_books[i], self.au_email)
```
Many issues here:
1. Redundant `au_name`, `au_email` and `au_user_books`. You will need to define something `self.x` only if `x` is required by some other functions/methods in the same class and you want to make it available in the whole class.
2. Bad returns `return print("...")`
3. Do you know there is a better way of looping: instead of `for i in range(0, len(self.au_user_books))` you can also do `for book in user_books`. Isn't this more intutive?

here is I would implement this function:
```
def add_user(self, name, email, user_books=None):
        new_user = User(name, email)
        self.users[email] = new_user
        if user_books:
            for book in user_books:
                self.add_book_to_user(book, email)
```

**Comment by skk1998** [comment]
Regarding the bullet points above,
1. I am aware of self.x being available for other methods/functions in the class. The variable names "name" "email" were used in lot of places within the class and it was getting confusing which was used where. So to simply the code which helped me debugging the problem i prefixed it with the function/method name e.g. prefix variable name with "au" in add_user.
3. Again this was coding practice to keep the code simple and manageable.
