### ISSUE TITLE
Rubric score

### ISSUE THREAD

**Issue by sen1** [skk1998/FireBird#8]
### Criteria 1: Valid Python Code
* 2 (Approaches Expectations)
* Good job on the project. There are a few things I mentioned in other issues which will make your code more efficient.
 
### Criteria 2: Implementation of Project Requirements
* 2 (Approaches Expectations)
* extra variables in classes were not asked in the requirement
 
### Criteria 3: Software Architecture
* 2 (Approaches Expectations)
* Lot of room for improvement. Good start.
 
### Criteria 4: Uses Python Language Features
* 3 (Meets Expectations)
* Good use of try-exceptions, dictonary and other methods.
 
### Overall Score: 9/16
Great work. Keep it up. This completes your review.

**Comment by skk1998** [comment]
Thanks for the review and comments.
